Boas práticas na construção de API
GustavoDeola/APIDesafio1Warren pull request #9
Opened 2022-06-21 18:50 UTC by GustavoDeola

2022-06-22 21:50 UTC, AlanMDomingues reviewed
Revisar comentários

2022-06-22 21:50 UTC, AlanMDomingues commented on APIDesafioWarren/Controllers/CustomerController.cs
> +
```suggestion
```
Linha em branco desnecessária

2022-06-22 21:50 UTC, AlanMDomingues commented on APIDesafioWarren/Controllers/CustomerController.cs
>          [HttpGet("Byemail/{email}")]
```suggestion
        [HttpGet("email/{email}")]
```
O padrão é sempre deixar em minúsculo e não precisa do 'By'.

2022-06-22 21:50 UTC, AlanMDomingues commented on APIDesafioWarren/Controllers/CustomerController.cs
>          [HttpGet("Bycpf/{cpf}")]
```suggestion
        [HttpGet("cpf/{cpf}")]
```
O padrão é sempre deixar em minúsculo e não precisa do 'By'.

2022-06-22 21:50 UTC, AlanMDomingues commented on APIDesafioWarren/Controllers/CustomerController.cs
>                      .GetAll(c => c.Equals(cpf));
```suggestion
                    .GetBy(c => c.Cpf.Equals(cpf));
```
Assim vai funcionar, pois está informando por qual campo você quer procurar o customer. Usar o GetBy porque retorna apenas um customer, pois você fez um método que impede que mais de um usuário tenha o mesmo CPF.

2022-06-22 21:50 UTC, AlanMDomingues commented on APIDesafioWarren/Controllers/CustomerController.cs
> +                var idCustomer = _customerAppService.Add(createCustomerRequest);
```suggestion
                var customerId = _customerAppService.Add(createCustomerRequest);
```

2022-06-22 21:50 UTC, AlanMDomingues commented on APIDesafioWarren/Controllers/CustomerController.cs
> +                : Created("~api/customer", $"Customer succefully registered! Your ID is: {idCustomer}");
```suggestion
                : Created("~api/customer", customerId);
```

2022-06-22 21:50 UTC, AlanMDomingues commented on AppServices/CustomerAppService.cs
> +            //return mapper.Id;
```suggestion
```
Para que serve esses comentários?

2022-06-22 21:50 UTC, AlanMDomingues commented on AppServices/ICustomerAppService.cs
>          Customer GetBy(Predicate<Customer> predicate);
```suggestion
        CustomerResponse GetBy(Predicate<Customer> predicate);
```

2022-06-22 21:50 UTC, AlanMDomingues commented on AppServices/CustomerAppService.cs
>          public Customer GetBy(Predicate<Customer> predicate)
```suggestion
        public CustomerResponse GetBy(Predicate<Customer> predicate)
```
Deveria retornar a DTO `CustomerResponse`

2022-06-22 21:50 UTC, AlanMDomingues commented on AppServices/Validations/CustomerValidator.cs
>                  .MaximumLength(30)
```suggestion
                .MaximumLength(300)
```

2022-06-22 21:50 UTC, AlanMDomingues commented on AppServices/Validations/CustomerValidator.cs
> +               .EmailAddress();
Deveria apenas validar se é igual ao Email.

2022-06-22 21:50 UTC, AlanMDomingues commented on AppServices/Validations/CustomerValidator.cs
>                  .EmailAddress();
```suggestion
                .EmailAddress(EmailValidationMode.Net4xRegex);
```

2022-06-22 21:50 UTC, AlanMDomingues commented on AppServices/Validations/CustomerValidator.cs
>              RuleFor(c => c.Cpf)
Recomendo adicionar a validação de CPF.

2022-06-22 21:50 UTC, AlanMDomingues commented on AppServices/Validations/CustomerValidator.cs
> -                .WithMessage("You must be at least 16 years old");
Por que apagou essa validação?

2022-06-22 21:50 UTC, AlanMDomingues commented on AppServices/Validations/StringExtensions.cs
> +            else if (validSpaces.Length > 0) return true;
Não precisa usar else if se você quer retornar true, todos ifs são as exceções, caso não caia em nenhuma ele vai cair em um único return true.

2022-06-22 21:50 UTC, AlanMDomingues commented on AppServices/Validations/StringExtensions.cs
> +        }
Seria melhor um método para fazer essa validação, porque você reutiliza ela em outros campos também. Boa prática de Clean Code.

2022-06-22 21:50 UTC, AlanMDomingues commented on Application.Models/DTOs/CreateCustomerRequest.cs
>  using System.Threading.Tasks;
Remover usings desnecessários, utilizar apenas System.
```suggestion
using System;
```

2022-06-22 21:50 UTC, AlanMDomingues commented on Application.Models/DTOs/CustomerResponse.cs
> +        //Response
```suggestion
```
Comentário desnecessário

2022-06-22 21:50 UTC, AlanMDomingues commented on ApplicationModels/ApplicationModels.csproj
> +    <Nullable>enable</Nullable>
```suggestion
```
Remover essas 2 linhas.

2022-06-22 21:50 UTC, AlanMDomingues commented on ApplicationModels/Class1.cs
> +}
```suggestion
```
Remover classe desnecessária.

2022-06-22 21:50 UTC, AlanMDomingues commented on Domain Models/Customer.cs
>      {
Renomear a classe para Domain.Models, não podemos usar espaço em classes.

2022-06-22 21:50 UTC, AlanMDomingues commented on DomainServices/Services/CustomerServices.cs
> +        private readonly List<Customer> _customersServices = new List<Customer>();
```suggestion
        private readonly List<Customer> _customerServices = new();
```
Podemos simplificar assim

2022-06-22 21:50 UTC, AlanMDomingues commented on DomainServices/Services/CustomerServices.cs
>              }
```suggestion
            }
            
```

2022-06-22 21:50 UTC, AlanMDomingues commented on DomainServices/Services/CustomerServices.cs
>              var cli = GetBy(c => c.Id == id);
```suggestion
            var customer = GetBy(c => c.Id == id);
```
Não podemos abreviar

2022-06-22 21:50 UTC, AlanMDomingues commented on DomainServices/Services/CustomerServices.cs
> +        private bool ValidCPF(Customer customer)
```suggestion
        private bool AnyCustomerForCpf(Customer customer)
```

2022-06-22 21:50 UTC, AlanMDomingues commented on DomainServices/Services/ICustomerServices.cs
> +        public bool Update(Customer customerChange);
```suggestion
        public bool Update(Customer customerToUpdate);
```

2022-06-22 21:50 UTC, AlanMDomingues commented on DomainServices/Services/CustomerServices.cs
> +        public bool Update(Customer customerChange)
```suggestion
        public bool Update(Customer customerToUpdate)
```

2022-06-22 21:50 UTC, AlanMDomingues commented on APIDesafioWarren/Controllers/CustomerController.cs
> +        public IActionResult GetByFullName(string fullname)
```suggestion
        public IActionResult GetByFullName(string fullName)
```

2022-06-22 21:50 UTC, AlanMDomingues commented on AppServices/CustomerAppService.cs
> +            //return mapper.Id;
```suggestion
```
Comentários desnecessários

2022-06-22 21:50 UTC, AlanMDomingues commented on AppServices/Validations/CustomerValidator.cs
> -                .WithMessage("Invalid cellphone");
Por que apagou essa validação? Podemos deixar o mínimo de caracteres como 10 e o máximo de caracteres como 11, para poder aceitar números com o 9 na frente ou não.

2022-06-22 21:50 UTC, AlanMDomingues commented on Application.Models/DTOs/UpdateCustomerRequest.cs
> +
```suggestion
```

2022-06-22 21:50 UTC, AlanMDomingues commented on Application.Models/DTOs/CustomerResponse.cs
> +
```suggestion
```

2022-06-22 21:50 UTC, AlanMDomingues commented on AppServices/Validations/CustomerValidator.cs
>              RuleFor(c => c.EmailConfirmation)
Email Confirmation deveria apenas validar se é igual ao Email.

2022-06-22 21:50 UTC, AlanMDomingues commented on AppServices/Validations/CustomerValidator.cs
> -                .WithMessage("Please complete this field");
Por que apagou essas validações?

2022-06-22 21:50 UTC, AlanMDomingues commented on Application.Models/DTOs/UpdateCustomerRequest.cs
> +        public int Id { get; set; }
```suggestion
```
Não enviar o ID

2022-06-22 21:50 UTC, AlanMDomingues commented on AppServices/Validations/CustomerValidator.cs
> +
```suggestion
```

2022-06-22 21:50 UTC, AlanMDomingues commented on AppServices/CustomerAppService.cs
>          public Customer GetBy(Predicate<Customer> predicate)
```suggestion
        public CustomerResponse GetBy(Predicate<Customer> predicate)
```
Devemos retornar a DTO `CustomerResponse`

2022-06-22 21:50 UTC, AlanMDomingues commented on AppServices/Validations/CustomerValidator.cs
>          }
Fazer essa validação direto no Fluent Validation

2022-06-22 21:50 UTC, AlanMDomingues commented on AppServices/Validations/CustomerValidator.cs
```suggestion
```
Linha em branco desnecessária

2022-06-22 21:50 UTC, AlanMDomingues commented on APIDesafioWarren/Controllers/CustomerController.cs
> +        public CustomersController(ICustomerAppService appServices, IMapper mapper)
```suggestion
        public CustomersController(ICustomerAppService customerAppService)
```

2022-06-22 21:50 UTC, AlanMDomingues commented on APIDesafioWarren/APIDesafioWarren.csproj
> -    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="11.0.0" />
Por que removeu?

2022-06-22 21:50 UTC, AlanMDomingues commented on AppServices/App.Services.csproj
> +    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="11.0.0" />
Remover esse pacote e adicionar o pacote do AutoMapper normal

2022-06-22 21:50 UTC, AlanMDomingues commented on DomainServices/Services/CustomerServices.cs
Remover essa classe e a interface dessa pasta `Services` e delete-a

2022-06-22 21:50 UTC, AlanMDomingues commented on Application.Models/DTOs/CreateCustomerRequest.cs
>  {
Renomear essa pasta para Requests, criar uma nova pasta chamada Responses e mover a classe CustomerResponse para ela.

2022-06-22 21:50 UTC, AlanMDomingues commented on APIDesafioWarren/Program.cs
> +var assemblie = new[] { Assembly.Load("App.Services") };
```suggestion
var assemblies = new[] { Assembly.Load("App.Services") };
```

2022-06-22 21:50 UTC, AlanMDomingues commented on AppServices/CustomerAppService.cs
> +        private readonly IMapper _mapper;
```suggestion
        private readonly ICustomerServices _customerService;
        private readonly IMapper _mapper;
```

2022-06-22 21:50 UTC, AlanMDomingues commented on AppServices/CustomerAppService.cs
> +            return _mapper.Map<IEnumerable<CustomerResponse>>(getAllCustomers);
```suggestion
            var customers = _customerService.GetAll(predicate);
            return _mapper.Map<IEnumerable<CustomerResponse>>(customers);
```

2022-06-22 21:50 UTC, AlanMDomingues commented on AppServices/CustomerAppService.cs
> +            return customerDTO;
```suggestion
            var customer = _customerService.GetBy(predicate);
            var result = _mapper.Map<Customer>(customer);
            return result;
```

2022-06-22 21:50 UTC, AlanMDomingues commented on AppServices/CustomerAppService.cs
> +            return _customerService.Update(mapper);
```suggestion
            var customer = _mapper.Map<Customer>(updateCustomerRequest);
            customer.Id = id;
            return _customerService.Update(customer);
```

2022-06-22 21:50 UTC, AlanMDomingues commented on AppServices/Helpers/CustomerProfile.cs
> +namespace AppServices.Helpers
```suggestion
namespace AppServices.Profiles
```
Renomear a pasta para Profiles

2022-06-22 21:50 UTC, AlanMDomingues commented on AppServices/Validations/CustomerValidator.cs
> +    public class CustomerValidator : AbstractValidator<CreateCustomerRequest>
Renomear para CreateCustomerValidator e fazer uma nova classe para validar o UpdateCustomerRequest chamado UpdateCustomerValidator.

2022-06-22 21:50 UTC, AlanMDomingues commented on AppServices/Validations/StringExtensions.cs
> +            return true;
```suggestion
            return !cpf.All(c => c.Equals(cpf.First()));
```

2022-06-22 21:50 UTC, AlanMDomingues commented on AppServices/Validations/StringExtensions.cs
> +        public static bool ValidCpf(this string cpf)
```suggestion
        public static bool AllCharacteresArentEqualsToTheFirstCharacter()(this string cpf)
```

2022-06-22 21:50 UTC, AlanMDomingues commented on AppServices/Validations/CustomerValidator.cs
>                  .Must(v => v.ValidPostalCode())
```suggestion
                .Must(v => v.AllCharacteresArentEqualsToTheFirstCharacter())
```

2022-06-22 21:50 UTC, AlanMDomingues commented on AppServices/Validations/CustomerValidator.cs
>                  .Must(v => v.ValidCpf())
```suggestion
                .Must(v => v.AllCharacteresArentEqualsToTheFirstCharacter())
```

2022-06-22 21:50 UTC, AlanMDomingues commented on AppServices/Validations/CustomerValidator.cs
> -                .Must(v => v.ValidCellphone())
`.Must(v => v.AllCharacteresArentEqualsToTheFirstCharacter())`

2022-06-22 21:50 UTC, AlanMDomingues commented on AppServices/Validations/CustomerValidator.cs
> -                .WithMessage("Please complete this field");
Por que apagou?

2022-06-23 02:44 UTC, AlanMDomingues reviewed
Padrão de commit está errado, devemos dar as informações do que foi feito.

2022-06-23 02:45 UTC, AlanMDomingues reviewed
Linhas em branco desnecessárias no final da controller

2022-06-30 21:29 UTC, ghost commented on APIDesafioWarren/APIDesafioWarren.csproj
> +    <ProjectReference Include="..\AppServices\App.Services.csproj" />
Mudou o nome do projeto mas faltou mudar o nome da pasta, vale ressaltar que o nome de acordo com a arquitetura é `Application`

2022-07-04 13:39 UTC, AlanMDomingues reviewed
Revisar novos comentários

2022-07-04 13:39 UTC, AlanMDomingues commented on AppServices/Validations/UpdateCustomerValidator.cs
> +        }
```suggestion
```
Não é necessário essa validação aqui, apenas no CreateCustomerValidator, que no caso você fez direto no FluentValidation, que é a maneira correta como foi sugerida

2022-07-04 13:39 UTC, AlanMDomingues commented on AppServices/Validations/StringExtensions.cs
> +        }
Não está cumprindo com o objetivo do método. O método está fazendo a mesma coisa que o IsValidString

2022-07-04 13:39 UTC, AlanMDomingues commented on AppServices/Validations/UpdateCustomerValidator.cs
> +                .Must(v => v.AllCharacteresArentEqualsToTheFirstCharacter())
```suggestion
                .Must(v => v.IsValidString)
```
Esse método já contém a validação anterior e mais outras validações

2022-07-04 13:39 UTC, AlanMDomingues commented on AppServices/Validations/UpdateCustomerValidator.cs
> +                .Must(v => v.AllCharacteresArentEqualsToTheFirstCharacter())
```suggestion
                .Must(v => v.IsValidString)
```
Esse método já contém a validação anterior e mais outras validações

2022-07-04 13:39 UTC, AlanMDomingues commented on AppServices/Validations/UpdateCustomerValidator.cs
> +                .Must(v => v.IsValidNumber());
Faltou inserir limite de caracteres

2022-07-04 13:39 UTC, AlanMDomingues commented on AppServices/Validations/UpdateCustomerValidator.cs
> +             .WithMessage("Please complete this field");
Faltou inserir limite de caracteres

2022-07-04 13:39 UTC, AlanMDomingues commented on AppServices/Validations/UpdateCustomerValidator.cs
> +                .WithMessage("Please complete this field");
```suggestion
            RuleFor(c => c.Number)
                .NotEmpty();
```
Sugiro que adicione uma validação para que o número for maior que 0

2022-07-04 13:39 UTC, AlanMDomingues commented on AppServices/Validations/UpdateCustomerValidator.cs
> +               .WithMessage("Invalid cellphone");
```suggestion
            RuleFor(c => c.Cellphone)
               .NotEmpty()
               .Must(v => v.IsValidString)
               .MinimumLength(10)
               .MaximumLength(11)
```

2022-07-04 13:39 UTC, AlanMDomingues commented on AppServices/Validations/UpdateCustomerValidator.cs
> +        }
Validação não está validando o mês e o dia, o código vai quebrar se o usuário colocar que nasceu dia 01/01 do ano em que faria 16 anos, não validando o mês e o dia em que faz aniversário.

2022-07-04 13:39 UTC, AlanMDomingues commented on DomainServices/Services/CustomerServices.cs
> +        private readonly List<Customer> _customersServices = new();
```suggestion
        private readonly List<Customer> _customers = new();
```
Estava correto dessa forma

2022-07-04 13:39 UTC, AlanMDomingues commented on AppServices/Profiles/CustomerProfile.cs
> +namespace AppServices.Helpers
```suggestion
namespace AppServices.Profiles
```
Faltou mudar o namespace de acordo com o nome da pasta em que foi inserido

2022-07-04 13:39 UTC, AlanMDomingues commented on AppServices/Validations/CreateCustomerValidator.cs
> +        {
Fazer as mesmas alterações do UpdateCustomerValidator nesta classe também.

2022-07-04 13:39 UTC, AlanMDomingues commented on AppServices/Validations/CreateCustomerValidator.cs
> +
```suggestion

        private static bool ValidBirthDate(DateTime birthdate)
        {
            var s = new DateTime(DateTime.Now.Year, birthdate.Month, birthdate.Day);
            var yearsDifference = s.Year - birthdate.Year;

            return yearsDifference >= 16;
        }
    }
}
```

2022-07-04 13:39 UTC, AlanMDomingues commented on AppServices/Validations/UpdateCustomerValidator.cs
> +        private static bool ValidBirthDate(DateTime birthdate)
```suggestion

            return firstDigitAfterDash == cpf.ToIntAt(^2) && secondDigitAfterDash == cpf.ToIntAt(^1);
        }
        
        private static bool ValidBirthDate(DateTime birthdate)
```

2022-07-08 17:18 UTC, ghost commented on Application.Models/Requests/CreateCustomerRequest.cs
> +        public string FullName { get; set; }
Só seria FullName se fossem 2 palavras separadas mas como fullname é uma só seria incorreto o N estar maiúsculo
```suggestion
        public string Fullname { get; set; }
```

2022-07-08 17:18 UTC, ghost commented on Application.Models/Requests/UpdateCustomerRequest.cs
> +        public string FullName { get; set; }
Mesmo comentário do de cima

2022-07-08 17:18 UTC, ghost commented on Application.Models/Response/CustomerResponse.cs
> +        public string FullName { get; set; }
Mesmo do de cima

2022-07-08 17:19 UTC, ghost requested changes

2022-07-08 17:19 UTC, ghost commented on Application/Application.csproj
> +
Camada de Application está duplicada, favor remover 1 delas

2022-07-08 17:20 UTC, ghost commented on ApplicationModels/ApplicationModels.csproj
> +    <Nullable>enable</Nullable>
Não foi removido ainda

2022-07-12 17:35 UTC, viniciusoliveira-warren commented on APIDesafioWarren/APIDesafioWarren.csproj
> +    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.15.1" />
Onde estamos usando esse pacote?

2022-07-12 18:05 UTC, viniciusoliveira-warren commented on Application.Models/Response/CustomerResponse.cs
> +        public string Fullname { get; set; }
FullName são 2 palavras, logo pascal case https://en.wiktionary.org/wiki/full_name
```suggestion
        public string FullName { get; set; }
```

2022-07-12 18:05 UTC, viniciusoliveira-warren commented on Application/Application.csproj
> +    <ProjectReference Include="..\Domain Models\Domain.Models.csproj" />
Desnecessário, já possui na camada de serviço
```suggestion
```

2022-07-12 18:09 UTC, viniciusoliveira-warren commented on Domain Models/Customer.cs
>      {
Acho que marcou como resolvido acidentalmente, o comentário do @AlanmWarren ainda é válido. @GustavoDeola

2022-07-12 18:51 UTC, viniciusoliveira-warren approved these changes

2022-07-12 18:59 UTC, merged